"""Frozen contracts: ports + Pydantic models.

This package never depends on any other workspace package. Every other package
imports its data models and `Protocol` ports from here.
"""

from rie_contracts.models import (
    AuthorityTier,
    BoundingBox,
    Claim,
    ClausePattern,
    CoverageRecord,
    CoverageState,
    Decomposition,
    DocumentMeta,
    DocumentProfile,
    DocumentType,
    Element,
    ElementType,
    EvaluationMethod,
    EvidenceSpan,
    GateName,
    GateResult,
    GoldItem,
    IndicatorConfig,
    Jurisdiction,
    Layer1Status,
    Layer2Recommendation,
    LegalRegime,
    OcrEngine,
    PillarConfig,
    RegistryEntry,
    RetrievalHit,
    ReviewDecision,
    ReviewRecord,
    ScoreBand,
    SourceRegistryEntry,
    SpanRole,
    StructureEdge,
    StructureEdgeType,
    VerificationReport,
    VerificationStatus,
)
from rie_contracts.ports import (
    ClassifierPort,
    ConfigRepositoryPort,
    CoverageReasonerPort,
    DocumentExtractorPort,
    DocumentRepositoryPort,
    EvaluatorPort,
    HumanReviewQueuePort,
    IngestPort,
    RerankerPort,
    RetrievalPort,
    StructureGraphBuilderPort,
    VectorStorePort,
    VerifierPort,
)

__all__ = [
    # Enums
    "AuthorityTier",
    "ClausePattern",
    "CoverageState",
    "DocumentProfile",
    "DocumentType",
    "ElementType",
    "EvaluationMethod",
    "GateName",
    "Jurisdiction",
    "Layer1Status",
    "OcrEngine",
    "ReviewDecision",
    "ScoreBand",
    "SpanRole",
    "StructureEdgeType",
    "VerificationStatus",
    # Models
    "BoundingBox",
    "Claim",
    "CoverageRecord",
    "Decomposition",
    "DocumentMeta",
    "Element",
    "EvidenceSpan",
    "GateResult",
    "GoldItem",
    "IndicatorConfig",
    "Layer2Recommendation",
    "LegalRegime",
    "PillarConfig",
    "RegistryEntry",
    "RetrievalHit",
    "ReviewRecord",
    "SourceRegistryEntry",
    "StructureEdge",
    "VerificationReport",
    # Ports
    "ClassifierPort",
    "ConfigRepositoryPort",
    "CoverageReasonerPort",
    "DocumentExtractorPort",
    "DocumentRepositoryPort",
    "EvaluatorPort",
    "HumanReviewQueuePort",
    "IngestPort",
    "RerankerPort",
    "RetrievalPort",
    "StructureGraphBuilderPort",
    "VectorStorePort",
    "VerifierPort",
]
